### ISSUE TITLE
Best Weather Integration vor platinium-weather-card

### ISSUE THREAD

**Issue by Nexow91** [Makin-Things/platinum-weather-card#111]
Hello, since I didn't know where to write this, I'll do it now under Feature Request: 

First of all, thank you very much for such a nice Loveace. 
Unfortunately, I have now integrated OpenWeatherMap + Weatherbit into Homeassistant to fill the Loveace with sensors for the respective parameters. Unfortunately, I can't find the sensors I need to fill all the content. 

For example: “Pearce Rain Chance 0”

Hence my question which integrations were used for the readme on the main page of the Github repo? Then I could also use these to fill the Loveace with data. 

If there are several, I would be happy to put them together. 

Thanks again for your work and I hope that I will soon get such a cool Loveace filled :)

**Comment by Nexow91** [comment]
?? no respone after 2 weeks ?

**Comment by Makin-Things** [comment]
It depends where in the world you live. Almost all can work with a little work. They are all implemented slightly differently and the way HA want weather integrations to function is less than ideal.

**Comment by Nexow91** [comment]
So thank you for the answer after 2 weeks of waiting. 

Can't you just tell me which integration you used? 

AccuWeather, Weatherbit, Openweathermap, Weatherflow.... and what else is out there. 

I have now tried 5 different integrations and each of them only provides part of the entities and even then the Lovelace is not completely filled. It must be possible to say what you have used. After all, you have written a complete wiki with the entities but which integration do you use? No plan... 


Then just saying yes it depends on where you live is a pretty relative answer that can't really relate to anything because the entities and their information come from the weather integration apps and not where I live because it's just longitude and latitude and not a whole information convult. 

If I'm wrong, I'll be happy to be proven wrong. 

Regards 

PS: something like the fire warning yes I agree with you that it may not exist in Germany, but a rain warning should probably be international.
