### ISSUE TITLE
Comments/Feature requests

### ISSUE THREAD

**Issue by Anwen747** [Makin-Things/platinum-weather-card#3]
I mentioned on the forum that I thought I saw a bug - that was user error on my part.  I do everything in YAML, and made a new dashboard to test out using the UI for this card.  Since I am not used to editing cards via the UI,  I missed a couple of things. One thing I am having trouble with is picking things from the dropdown menus, some of them disappear when I try to scroll down/choose an item. Maybe this is a UI editor thing in general as opposed to an issue with the card.  When the card is finally released, I will be using YAML configuration for it.

Not sure if you are planning on keeping these previous features in the new card, maybe you are, but here's my input:

_Option for static icons_ - This is important to me, I really dislike the animated icons.

_Different icon sets_ - not sure what your plans are for icons, as I know David added a bunch, but I currently have the option set for old icons only, and would like to be able to keep that if possible.

_Slot section_ - This is not super important, but I currently use the right-justified option (old column format = true).  I know David's documentation does not recommend that format, but I don't know why.  If nobody else wants this, or it is a pain to implement, I can get used to the new format.

Really happy to have the custom slots, as I use one for dew point.

Thanks very much for all your work on this card, it's one of my favorites, and I am really happy it is getting a new lease on life 🙂

**Comment by Makin-Things** [comment]
For the dropdown problem, have you updated to HA 2022.6 yet? The recent updates to Chrome actually broke HA in mid/late May and it was fixed in the June release. For migration you should be able to cut/paste your entire yaml config from the old card and paste it in as yaml to the new card. The new card at some point will remove unused config items.

The icon stuff will be in there. I have a reminder in the list in #1 (and a scribbled list on a bit of paper sitting in front of me).

Once again the old format will be in there, but it may move things slightly as I have massively updated the html to allow various other things to work properly (such as reordering and hiding sections). There needed to be consistency, particularly for vertical spacing.  The reason we are not a fan of right justifying things is that the entire right hand column will move about as data updates, which end up looking weird.

**Comment by Anwen747** [comment]
I am still on 2022.5.5, using Microsoft Edge as a browser.  I usually wait for a couple of point releases before I update.  I will be updating when they release 2022.6.3, because a fix for my recent GitHub issue with a Climacell/tomorrow.io time zone problem will be in that release.  I will check and see if the dropdown menus work better then.

It is definitely convenient to be able to copy the YAML from the UI editor to create my card.  I've been using HA for more than 4 years, since before the UI even existed, so YAML feels normal to me.

Great to hear the features I like will be included.  The spinning pulsating sun icon makes me dizzy 🤣 I guess my right-hand column isn't an issue for me, as the items I have in it are pretty consistent in size, so I don't notice it moving around.  It's not a critical feature, just what I am used to after all this time.  I've been using the card ever since it was developed for Dark Sky, probably almost as long as I've been using HA.

If there is anything I can do to help with testing the card, I am happy to help.

**Comment by DavidFW1960** [comment]
our goal was to make the new card 100% compatible with the old yaml config. We have decided to ditch the old alt variables as no one has responded when we sought comments on that and it massively complicates everything. You should right now be able to add the new card, switch to yaml mode and paste your current configuration and it will work and look 99% the same as before.

**Comment by Makin-Things** [comment]
Ok, you will probably be affected by the browser update (it affects any Chromium based browser that has been updated recently). When you move the mouse around over the dropdown you will see the mouse pointer change to match what is behind the dropdown, and any click goes to whatever is behind.

Best thing to do is exactly this, report any problems you see, suggest features etc. At the moment I am working on getting all the existing things working and ironing out layout issues. Before maybe adding a few little extras.

I am going to be rewriting the doco soon, but have been holding off as it needs to include screen shots and I don't want to do that until things have stopped changing. I will be looking for people to review that when I get there.

**Comment by DavidFW1960** [comment]
> I know David's documentation does not recommend that format, but I don't know why. If nobody else wants this, or it is a pain to implement, I can get used to the new format.

I'm going to blame Simon for this but will say we were very surprised at the pushback we got when we changed it to be left justified hence we made it an option to revert.

**Comment by Anwen747** [comment]
Updated to 2022.6.3 and dropdown menus seem to be working okay now.

David, I used to use the alt variables for the wind slot before I switched to the BOM card, but your card does that automagically so no more alts needed :)

I tried adding the new card and dropping in my current YAML config, and the only thing that is wrong is that the extended section (in which I am not using fire danger or UV, only entity daily summary) is above the slots instead of at the bottom.

I have been playing around with theming today and discovered that the forecast low temperatures in the old card are done with secondary-text-color. Everything else seems to be primary-text-color.  Looks quite odd depending on the chosen secondary color!  The new card seems to be all primary-text-color, which is much better, so hooray for that.

I have been told that I am a good proof-reader, am happy to read over documentation when it is ready.

**Comment by DavidFW1960** [comment]
> is above the slots instead of at the bottom.

You can move it. That's what the up/down arrows on the right do. Apart from some font sizes, my old card looks identical to the new one on my system.

> forecast low temperatures in the old card are done with secondary-text-color.

I think you're going to be able to change that with the styling options. Or you can use card-mod. Every element is it's own class now.

> I have been told that I am a good proof-reader, am happy to read over documentation when it is ready.

I think Simon is working on this soon and everything will be in this repo until we are ready to push the new card. (old one will continue to be available)

**Comment by Anwen747** [comment]
Yup, had already figured out how to move it down in the card I configured with the UI.  Only mentioned it because I thought you were trying to make the new card a drop-in replacement for the old one, and that is the one change I saw.

**Comment by DavidFW1960** [comment]
> Only mentioned it because I thought you were trying to make the new card a drop-in replacement for the old one

Good point. We should change the default.

**Comment by Anwen747** [comment]
Today I have been playing with making a card with my weather station data on it:

![ws_card2](https://user-images.githubusercontent.com/51857150/172704239-780a9a35-697f-4227-9ed5-c3f1307f5e56.jpg)

Everything but the top section icon, current text, and pop come from my backyard weather station.  I wish I had had at least 2 additional custom slots.  I templated the UV slot (slot L2) so that works fine.  I've used the pop slot (slot L3) to put in today's recorded rainfall, and used today's recorded rainfall (slot L4) to put in the hourly rain rate (in/h) - so the icon works but the units don't.  I made another template sensor to put additional data at the bottom.  I have plenty of unused slots available, but none of the unused sensor possibilities make any sense for any of those items.  Any possibility of getting more custom slots?

One thing we had before that needs to be added - I need the additional decimal places for barometric pressure.  So far that doesn't seem to be an option in the new card.

Also, we used to be able to move the Current Conditions string - I had changed mine to have a smaller top margin, because I think it feels too low.  Wondering if this will be an option in the new card (or if it will be able to be done with card-mod).

Hope I am not driving you crazy 😊 
Many thanks, Anwen

**Comment by Makin-Things** [comment]
A lot of the miscellaneous options haven't been migrated yet. They will be added over time. I suggest you keep an eye on #1 as it has a list of things that I know aren't done. I Update that regularly as I think of things or actually do one of them.

Card-mod should be able to do almost anything. There are classes assigned consistently to all elements. But something doesn't look right with the spacing of the current text as there should not be that much space.

**Comment by Makin-Things** [comment]
I got more of the options added today, and added a more detailed sub-list in #1 of things I know aren't done yet. Please do an update and check the list and comment on options you think I aren't either done or on the list.

**Comment by Makin-Things** [comment]
Yeah, I renamed it to overview and that broke things slightly. Go into the code editor find this:
```section_order:
  - title
  - main
  - extended
  - slots
  - daily_forecast
 ```
and change main to overview (or just delete the section entirely and it will get added back correctly the next time you edit.

**Comment by Anwen747** [comment]
That was an easy fix!

**Comment by Makin-Things** [comment]
It will now add missing items back at the bottom of the list. Things will be out of order but at least it will be there. In reality that should only ever happen if someone fiddles with the yaml. It also make it easier for me to add new sections (such as daily forecast) as I just have to define it and magically it will get added to the bottom of the editor.

**Comment by Anwen747** [comment]
Sounds good - card is coming along great!  Very happy to have the additional custom slots.  I still see the issue with the date being wrong in the title section.

**Comment by Anwen747** [comment]
I was playing with looking at the different icon sets.  I have set my cards back to using the old icons, but no amount of "empty cache and hard reload" gets me back to having the old icon set.  I tried deleting both cards, clearing cache a few times, and creating the cards again.  I still see the new icons when my cards are set to use the old ones.  Any ideas?

**Comment by DavidFW1960** [comment]
> I was playing with looking at the different icon sets. I have set my cards back to using the old icons, but no amount of "empty cache and hard reload" gets me back to having the old icon set. I tried deleting both cards, clearing cache a few times, and creating the cards again. I still see the new icons when my cards are set to use the old ones. Any ideas?

I had a similar issue the other night after Simon changed an icon.

**Comment by Makin-Things** [comment]
Old icons are fixed. I forgot to change something when I was tidying up that option.

**Comment by Makin-Things** [comment]
Closing as I believe it is resolved.
