### ISSUE TITLE
Card not appearing with HA 2022.7.1

### ISSUE THREAD

**Issue by jeffjensen** [Makin-Things/platinum-weather-card#30]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
0.0.3

**Last working release (if known):**
0.0.3b2
(it installed, ran and some things worked, but had issues)

**Browser and Operating System:**
Brave Win 10

**Description of problem:**
After upgrading to HA 2022.7.1 (I skipped 2022.7.0, issue may have occurred with it too), this card no longer works.  The Dashboard I had the card on displayed a "card not found" error.  It also no longer appears in the dashboard editing cards list to add.  

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
1. Other custom cards work fine.
2. Restarts and full HAOS reboot had no impact.

**Comment by erkr** [comment]
Yep, in HACS I see the same:
![image](https://user-images.githubusercontent.com/4363599/178046463-e0637381-fdad-49b9-9b7c-e0fc5671595f.jpeg)
But the card is actually loaded in Lovelace and seems to work

**Comment by jeffjensen** [comment]
Restarting fixes the "Not Loaded".  The card does not appear for me nor work.

**Comment by bkr1969** [comment]
Perhaps releasing a "Beta" version should be delayed until the alpha testing is done and there's actually a working card for people to use.

**Comment by DavidFW1960** [comment]
> Perhaps releasing a "Beta" version should be delayed until the alpha testing is done and there's actually a working card for people to use.

This is a fully working version.
Try downloading it again via HACS. Looks to me like the resource didn't get added correctly. I think this is an issue with HA 2022.7.x as I saw similar.

**Comment by jeffjensen** [comment]
In HACS, I removed this card repo and downloaded again.  The card still does not appear for adding in the list.

**Comment by DavidFW1960** [comment]
cleared cache and hard reset?

**Comment by Gerbildral** [comment]
i just added the card with HACS, but it doesn't show up after a hard reset, restart or with a clear cache

**Comment by Jefe2** [comment]
An update to HACS became available a few hours ago.  For me, updating HACS to 1.26.0 has resolved issues with loading version 0.0.3 of the card.

**Comment by Gerbildral** [comment]
i also just updated HACS but i still get the "not loaded" error

**Comment by jeffjensen** [comment]
The card appears in the "Add Card List" and on Dashboard again for me.  Similar to @Jefe2 , my recipe is:

1. Updated HACS to 1.26.0.
2. Restart.
3. Redownload platinum-weather-card.

Then the card appeared in the list for selecting.

**Comment by erkr** [comment]
Yes, updating Hacs solved it for me

**Comment by Gerbildral** [comment]
yes, i had to redownload it. But now it works

**Comment by Makin-Things** [comment]
Fixed by HACS 1.26. Closing.
