### ISSUE TITLE
FR:,Ability to hide real estate that is not used

### ISSUE THREAD

**Issue by erkr** [Makin-Things/platinum-weather-card#33]
Now the card is working very well, a feature request as a change😉

While using the card with a standard weather sensor, there is quite a lot of unused space in the header part (marked with orange cirkels)
It works be nice if these areas can be hidden to safe screen space (especially useful on the mobile)

Update: only the first circle, the second is already configurable! Sorry

![image](https://user-images.githubusercontent.com/4363599/178312854-44af5c77-7011-4bf8-8143-1a50f9db8a7c.jpeg)

**Comment by Makin-Things** [comment]
The space below the word cloudy is removed by disabling sections you aren't using. The space above can't and won't be reduced as a lot of the icons drop down a lot lower (ie. when it is raining there is actual rain shown falling out of the cloud) and the text can extend to the full width of the screen.
