### ISSUE TITLE
Enhance apparent temperature 

### ISSUE THREAD

**Issue by cdn4lf** [Makin-Things/platinum-weather-card#38]
**Is your feature request related to a problem? Please describe.**
Please add /enhance apparent temperature. Environment Canada uses a humidex value (temp plus humidity factor) for warm weather and wind chill (temp minus wind speed) as 2 different values. Currently only one can be selected 

**Describe the solution you'd like**
It would be nice if apparent temperature could be set for both and switch based on the current populated value.

**Comment by Makin-Things** [comment]
If you have a sensor that provide apparent temperature it can be set as the value  for ``feels like``.
Apparent temp/feels like is a calculated number (as opposed to something measured). It is based off temperature/humidity/windspeed. This is something that needs to be created as a template sensor if not already made available with your weather integration.

**Comment by cdn4lf** [comment]
I'm already doing this, but one value returns null currently the other is
populated. (See screenshot attached)

It would be nice if both could be accommodated with the logic to only show
the populated one.

**Comment by Makin-Things** [comment]
Front end cards will only display data from backend sensors. The card can only display data provided by your sensors. If they are not right there is no chance of the card fixing it. You need to get your sensors right.

**Comment by cdn4lf** [comment]
The sensors are right, but based on the season only one shows data at a time.  

I can manually reconfigure the card twice a year, but that seems excessive.

**Comment by Makin-Things** [comment]
Well the card can't guess that. So maybe you need to create a template sensor with the smarts built in and provide that to the card.

**Comment by cdn4lf** [comment]
Will do. Wasn't sure if the card would be able to do this or not.

Thanks for considering it.

**Comment by Makin-Things** [comment]
Cards in general can only consume the data passed to them. So weirdness like this is better handled in the back end.
