### ISSUE TITLE
Current condition icon doesn't load

### ISSUE THREAD

**Issue by cdn4lf** [Makin-Things/platinum-weather-card#39]
**Checklist:**

- [ x] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**
0.03

**Last working release (if known):**
Unknown 
**Browser and Operating System:**
Chrome/mobile app 

**Description of problem:**
When weather entity set, icon displays as hazard/caution sign only.

```
card_config_version: 4
daily_forecast_days: 5
entity_apparent_temp: sensor.toronto_humidex
entity_current_conditions: sensor.toronto_current_condition
entity_current_text: sensor.toronto_current_condition
entity_daily_summary: sensor.toronto_summary
entity_forecast_high_temp_1: weather.toronto
entity_forecast_icon_1: weather.toronto
entity_forecast_low_temp_1: weather.toronto
entity_forecast_max: sensor.toronto_high_temperature
entity_forecast_min: sensor.toronto_low_temperature
entity_humidity: sensor.toronto_humidity
entity_pop: sensor.toronto_chance_of_precipitation
entity_pop_1: weather.toronto
entity_possible_today: sensor.toronto_chance_of_precipitation
entity_pressure: sensor.toronto_barometric_pressure
entity_sun: sun.sun
entity_temperature: weather.toronto
entity_uv_alert_summary: sensor.toronto_uv_index
entity_wind_bearing: sensor.toronto_wind_bearing
entity_wind_gust: sensor.toronto_wind_gust
entity_wind_speed: sensor.toronto_wind_speed
extended_use_attr: false
option_icon_set: new
option_pressure_decimals: 1
option_static_icons: false
option_today_decimals: true
option_tooltips: true
section_order:
  - title
  - overview
  - extended
  - slots
  - daily_forecast
show_decimals: true
show_section_title: false
show_separator: true
slot_l1: forecast_max
slot_l2: forecast_min
slot_l3: wind
slot_l4: pressure
slot_l5: sun_next
slot_l6: remove
slot_l7: remove
slot_l8: remove
slot_r1: pop
slot_r2: humidity
slot_r3: uv_summary
slot_r4: empty
slot_r5: sun_following
slot_r6: remove
slot_r7: remove
slot_r8: remove
type: custom:platinum-weather-card
```
**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
![Screenshot_20220724-061955_Home Assistant](https://user-images.githubusercontent.com/49874417/180642755-fb188733-566c-440c-8881-4ff4f14fd33b.jpg)

**Comment by Makin-Things** [comment]
I am currently reworking and enhancing the icons being used. But this is not expected. Can I ask what the state of ``weather.toronto`` is.

**Comment by cdn4lf** [comment]
Full output is attached as a screenshot.  Happy to test as needed.

**Comment by Makin-Things** [comment]
Please show the state as shown in ``developer tools``

**Comment by cdn4lf** [comment]
partlycloudy. The screenshot is the entire developer tool data/attributes
of weather.toronto

**Comment by Makin-Things** [comment]
Ok. That looks like a proper bug after a quick look. It appears that ``partlycloudy`` isn't being handled properly. It's close to midnight here now so I will do a fix tomorrow.

**Comment by Makin-Things** [comment]
Ok, I was really tired when looking at this last night. It's not a bug, you are using the wrong entity.
![image](https://user-images.githubusercontent.com/91187456/180669826-12135fd4-ebaf-42e0-94fc-70e2eb583a77.png)
Change this to use weather.toronto

**Comment by cdn4lf** [comment]
That worked.

May want to include in the docs that if there is a current conditions
entity to use the weather one.

The rest of this looks good. Really slick.

**Comment by Makin-Things** [comment]
I am currently reworking the whole icon part of the card to add flexibility. I haven't done the documentation for the overview part as I would probably have to completely redo it.

**Comment by cdn4lf** [comment]
Makes sense. It's looking really good and wasn't too complicated to figure
out.

Thanks for working on this, excited to use it.
