### ISSUE TITLE
Doesn't work in UK

### ISSUE THREAD

**Issue by quiggles** [Makin-Things/platinum-weather-card#41]
Latest version of everything in HA, but card doesn't show any details
![weather](https://user-images.githubusercontent.com/3470029/180758856-f8f85c9c-5d1e-4431-b743-89b6c655d240.png)

**Comment by Makin-Things** [comment]
You need to tell it what entities to use. The card can't just guess that.

**Comment by Steve-gnome** [comment]
not exactly obvious how one actually goes about doing that,....

**Comment by DavidFW1960** [comment]
So use the editor and its pretty straightforward

**Comment by oz9els** [comment]
Sorry, but none of you are very helpfull - Neither me, nor [quiggles](https://github.com/quiggles) knows what "entities to use" or where to "use the editor". 
My guess: Somewhere in the "Global Options" there would be a _Service to use_ - Here I would put **weather.home**

**Comment by quiggles** [comment]
Thanks oz9els - exactly this! What entities and where!

**Comment by Steve-gnome** [comment]
> Sorry, but none of you are very helpfull - Neither me, nor [quiggles](https://github.com/quiggles) knows what "entities to use" or where to "use the editor".
> My guess: Somewhere in the "Global Options" there would be a _Service to use_ - Here I would put **weather.home**

Yup - my point exactly.

**Comment by DavidFW1960** [comment]
The card configuration options (all behind the pencil icons) allow you to specify the entities. The documentation is a work in progress but honestly it's not rocket science and very intuitive if you work through the configuration screens (behind the pencil icons). See the readme.md on the code page for some limited examples. Many people have worked this out with less informayion...

**Comment by quiggles** [comment]
"Many people have worked this out with less informayion..."

Thanks for calling us stupid - uninstalling this card.

**Comment by Makin-Things** [comment]
So you never provided any information about your config what weather integration you are using or anything else useful. There is no chance of us providing any assistance if the only things you say is  'Doesn't work in UK'.
