### ISSUE TITLE
yaml mode 

### ISSUE THREAD

**Issue by DrSpaldo** [Makin-Things/platinum-weather-card#42]
Hi, I realise in the docs you say you prefer people didn't use yaml mode and they use the UI editor. Unfortunately we all can't use that editor and some of us are stuck with yaml mode only:

![2022-07-26 screenshot](https://user-images.githubusercontent.com/8526509/180917559-64cc4a1b-c5d1-44ce-9d4f-485b318e0387.jpg)

I was hoping someone may be able to point me in the direction of what some of the yaml config options are?

**Comment by DavidFW1960** [comment]
Most of the options here https://github.com/DavidFW1960/bom-weather-card should work until we get this documented here. Or create a new dashboard in GUI mode and cut/paste

**Comment by Makin-Things** [comment]
I have added a yaml reference at the end of the README file.

**Comment by DrSpaldo** [comment]
Thanks @Makin-Things
