### ISSUE TITLE
Wrong weather units

### ISSUE THREAD

**Issue by ricmik** [Makin-Things/platinum-weather-card#44]
With the possibility to change weather units in release 2022.7 of Home Assistant, the card should also show the configured unit for the weather entity and not be hard-coded.

**Weather Card**
![image](https://user-images.githubusercontent.com/6681390/182549319-8e280aa1-4588-42f4-b0ea-259e3428da71.png)

**Weather entity**
![image](https://user-images.githubusercontent.com/6681390/182549422-bf0fad91-38a3-45ee-bd74-edf3f515fc7b.png)

**Comment by Makin-Things** [comment]
This unit override stuff that was introduced in 2022.7 doesn't work on regular entities (only attributes within a weather.xxx have this feature). As such I can't change the behaviour as quite a lot of weather integrations create additional entities. There is also a lack of device classes (ie. wind speed or speed don't exist). Until the HA devs decide to address this there is nothing I can do.

**Comment by ricmik** [comment]
> Until the HA devs decide to address this there is nothing I can do.

What about allowing to specify the unit for the entity in the card directly?
