### ISSUE TITLE
wind_speed

### ISSUE THREAD

**Issue by Elektronik777** [Makin-Things/platinum-weather-card#50]
Hello. Thank you so much for such a wonderful card. I really liked it. 
In our region, wind plays a very important role in the state of the weather.
Please add the wind forecast to the Daily Forecast Section. 
(Integration ha-gismeteo, wind_speed, units of measurement - meters per second (m/s or м/с).
In advance thanks.

**Comment by Makin-Things** [comment]
Sorry, but I will not be doing any work for Russian integrations until such time as Putin leaves Ukraine.

**Comment by johndoe0815** [comment]
I would appreciate the same for open weather map. I would find it htlpful to see the wind speed for the next days, as in case of wind speeds over 40kmh I need to take some safety measures in the garden.
