### ISSUE TITLE
color of the figure: wind speed, temperature, temperature feels like

### ISSUE THREAD

**Issue by Elektronik777** [Makin-Things/platinum-weather-card#51]
It would be nice if the color of the figure (wind speed, temperature, temperature feels like , geomagnetic activity) could be changed depending on the value. 
For example, if the wind is more than 7 m / s - yellow, if above 10 m / s - bold red. Or flashing.  

So that it immediately catches the eye - hey guy, it's cold today. Put gloves and a hat on the child.

Thank you in advance

**Comment by Makin-Things** [comment]
Sorry, but I will not be implementing this. All of the elements in the card have classes assigned so if you are desperate you can use card-mod to do this.
