### ISSUE TITLE
unit decimals

### ISSUE THREAD

**Issue by degrepi** [Makin-Things/platinum-weather-card#52]
Hello,
many compliments for the beautiful card. Can you put decimals to Wind and Wind gust entity and put the seconds on Next sun rise and following sun rise ? This is what I mean, many thanks
![weather card](https://user-images.githubusercontent.com/111336823/188811435-11af1eaa-20b6-4194-872c-cd04359bab57.png)

**Comment by Makin-Things** [comment]
Sorry, but I will not be making this change as there is very little value in doing so for items that are so variable.

**Comment by degrepi** [comment]
Thank you very much

*Giuseppe De Gregorio M.D.*

Piazza V. Cuoco, 2 – 86100 Campobasso (CB)

( : +39* 329 0546168* - Tel/Fax: +39 *0874 311805*

› ***@***.***

: https://de-gregorio-dr-giuseppe.business.site/


Il giorno dom 18 set 2022 alle ore 10:22 Simon ***@***.***>
ha scritto:
