### ISSUE TITLE
State names

### ISSUE THREAD

**Issue by Nubstex** [Makin-Things/platinum-weather-card#53]
![image](https://user-images.githubusercontent.com/91033840/191093454-4b4707e2-0571-4692-826e-3b61d9ac0f46.png)

Is there any way to display the status with a capital letter? Translating into Polish makes the state written in lowercase and it looks ugly. Maybe you add a function to change it?

**Comment by Nubstex** [comment]
And i think that you can change "Najwyższa dziś" to "Temperatura maks." and "Najniższa dziś" to "Temperatura min." but it is only my opinion :)

**Comment by Makin-Things** [comment]
Fixing the non-capitalised summary is something that is on my todo list. It's not simple though as the translated strings are provided by the HA core.

With the correction of the min/max I am happy to do it. My Polish is non-existent. I think those translations came from a previous version of the card. Playing with google translate I get the following.
![image](https://user-images.githubusercontent.com/91187456/191623387-534f7263-52ef-4d5c-a311-7b305415fac1.png)
So should it be 'Tempertura Maks' or 'Maks Tempertura'?

**Comment by Makin-Things** [comment]
I have had a further look at this. The problem with the summary text is that the Polish translations provided by HA are not capitalised correctly (every other language I look at is). So this is a problem stemming from HA that I am not able to fix. It should be done in the HA frontend. It is also not just weather translations but all translations provided by HA.
You should be seeing capitalisation missing all over the place. I'd suggest raising an issue against the HA Frontend project where there translations come from.
This is the file that I believe needs updating to fix the ugliness.
https://github.com/home-assistant/frontend/blob/dev/translations/backend/pl.json

Let me know about the min/max stuff still as those are translations within the platinum card.

**Comment by Nubstex** [comment]
I think "Maksymalnie X°C" and "Minimalnie X°C" would look better especially on mobile devices :)

**Comment by Makin-Things** [comment]
Updated in 0.0.5.

**Comment by Nubstex** [comment]
Hi, that's me, again. I changed your card and i think it looks great. Look:
![image](https://user-images.githubusercontent.com/91033840/196691039-8d1c575a-2aa9-48e4-8d85-d50573cdc148.png)
