### ISSUE TITLE
Warnings displayed but card working?

### ISSUE THREAD

**Issue by balkonrad** [Makin-Things/platinum-weather-card#62]
**Checklist:**

- [|] I updated to the latest version available
- [|] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):** From beginning

**Browser and Operating System:** Chrome / Windows 11

**Description of problem:**
![Screenshot_1](https://user-images.githubusercontent.com/6885412/196915634-8f73b8a3-2c89-4815-a156-786781e39ee8.png)

**Javascript errors shown in the web inspector (if applicable):**

No errors

**Additional information:**

**Comment by balkonrad** [comment]
Still the same : 
![image](https://user-images.githubusercontent.com/6885412/196928320-3ac19695-0c13-4657-8703-b488edf53075.png)

I'm using accuweather integration.

**Comment by balkonrad** [comment]
Issue to be closed - for accuweather it is needed to change this setting:

![image](https://user-images.githubusercontent.com/6885412/197027965-31b1f73d-b993-4101-947e-ba85e01ccb4c.png)

**Comment by Makin-Things** [comment]
I will have a further look at this. If there is less than 5 days of forecast (starting from tomorrow) it is meant to automatically reduce the number of days shown.
Are you able to share a screenshot of your weather.xxx sensor (with all of its attributes) from the developer tools.

**Comment by Makin-Things** [comment]
Nevermind, I figured it out and it will not show those warnings in the next release.
