### ISSUE TITLE
Minor formatting issues

### ISSUE THREAD

**Issue by craigueh** [Makin-Things/platinum-weather-card#63]
Could we get some minor formatting tweaks or options added?

1. Can the Current Condition text such as Cloudy be left aligned under the Current Condition icon? Or an option for left, middle, right alignment perhaps? It looks odd for it to be randomly in the middle of the page on larger screens so some alignment left or right would look better depending on peoples preference.

2. The Extended section, can we have line breaks or similar after each section as currently they are all merged together as one line?
Or alternatively an option to add subsequent sections as required? 
See below: 

_TODAY - Thursday 20th October,Largely dry and sunny this afternoon and it will be mild for October with highest temperatures of 15 to 17 degrees. TONIGHT,A dry start to the night but rain will spread from the south later. Lowest temperatures of 10 to 13 degrees with fresh and gusty east or southeast winds._ 

This summary is made up from multiple scrape sensors to get forecast dates and data but they are all merged together as one line of text. if there was a way to add sections as required with line breaks between them that would be great.

3. The slots section alignment of the right side items looks odd on larger screens. Can an option be added to align right like on the original Weather Card as this looks much better than middle aligned I think but others may have a different preference.

Thanks.

**Comment by Makin-Things** [comment]
I feel that if I were to make any of these changes I would then get complaints and ask why it was changed. I unfortunately don't have the time to be able to spend on the card for now other than fixing genuine bugs.
