### ISSUE TITLE
Not displaying when rainfall forecast is included

### ISSUE THREAD

**Issue by erunaheru** [Makin-Things/platinum-weather-card#64]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

Release: 1.0.0

Last Working Release: I think 0.0.4

Brave, Windows 11

**Description of problem:**

When the "rainfall forecast" slot is selected, the entire card fails to display. The value was 0 when the problem was noticed, so that may impact it. I had an error icon instead of the weather icon and opened and saved the configuration as mentioned in the release notes, the error began immediately after.

**Javascript errors shown in the web inspector (if applicable):**

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'attributes')
    at get slotPopForecast [as slotPopForecast] (platinum-weather-card-52f94d57.js:279:3840)
    at fe.slotValue (platinum-weather-card-52f94d57.js:279:1378)
    at get slotR1 [as slotR1] (platinum-weather-card-52f94d57.js:279:822)
    at fe._renderSlotsSection (platinum-weather-card-52f94d57.js:163:22)
    at platinum-weather-card-52f94d57.js:268:1325
    at Array.forEach (<anonymous>)
    at fe.render (platinum-weather-card-52f94d57.js:268:1160)
    at fe.update (platinum-weather-card-52f94d57.js:47:547)
    at fe.performUpdate (platinum-weather-card-52f94d57.js:41:4839)
    at fe.scheduleUpdate (platinum-weather-card-52f94d57.js:41:4486)

**Additional information:**

Data from weather entity:

{"entity_id":"weather.openweathermap","state":"clear-night","attributes":{"temperature":35,"temperature_unit":"°F","humidity":86,"pressure":30.21,"pressure_unit":"inHg","wind_bearing":0,"wind_speed":0,"wind_speed_unit":"mph","visibility_unit":"mi","precipitation_unit":"in","forecast":[{"condition":"sunny","precipitation_probability":0,"datetime":"2022-10-22T16:00:00+00:00","wind_bearing":129,"temperature":68,"templow":35,"pressure":30.21,"wind_speed":7.63,"precipitation":0},{"condition":"cloudy","precipitation_probability":0,"datetime":"2022-10-23T16:00:00+00:00","wind_bearing":322,"temperature":69,"templow":44,"pressure":30.24,"wind_speed":3.09,"precipitation":0},{"condition":"sunny","precipitation_probability":0,"datetime":"2022-10-24T16:00:00+00:00","wind_bearing":136,"temperature":72,"templow":44,"pressure":30.21,"wind_speed":4.03,"precipitation":0},{"condition":"partlycloudy","precipitation_probability":0,"datetime":"2022-10-25T16:00:00+00:00","wind_bearing":134,"temperature":72,"templow":47,"pressure":30.12,"wind_speed":6.11,"precipitation":0},{"condition":"rainy","precipitation_probability":100,"datetime":"2022-10-26T16:00:00+00:00","wind_bearing":120,"temperature":63,"templow":57,"pressure":29.94,"wind_speed":3.18,"precipitation":0.46},{"condition":"rainy","precipitation_probability":100,"datetime":"2022-10-27T16:00:00+00:00","wind_bearing":15,"temperature":72,"templow":58,"pressure":29.94,"wind_speed":5.26,"precipitation":0.36},{"condition":"cloudy","precipitation_probability":9,"datetime":"2022-10-28T16:00:00+00:00","wind_bearing":20,"temperature":63,"templow":57,"pressure":30.12,"wind_speed":4.94,"precipitation":0},{"condition":"rainy","precipitation_probability":79,"datetime":"2022-10-29T16:00:00+00:00","wind_bearing":82,"temperature":56,"templow":52,"pressure":30.24,"wind_speed":6.08,"precipitation":0.06}],"attribution":"Data provided by OpenWeatherMap","friendly_name":"OpenWeatherMap"},"last_changed":"2022-10-22T00:46:46.476Z","last_updated":"2022-10-22T06:06:48.428Z","timeSinceChangedMs":20367271}

**Comment by Makin-Things** [comment]
I found I had introduced a typo in the code for that. I have done a new release (1.0.1) that fixes it.
Can you please test.

**Comment by erunaheru** [comment]
Looks like that fixed it!

**Comment by erunaheru** [comment]
Just wanted to say thanks for making this card, it's awesome!
