### ISSUE TITLE
Virtually no options available? Broken by 2022.11

### ISSUE THREAD

**Issue by chicknlil** [Makin-Things/platinum-weather-card#67]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
1.0.2

**Last working release (if known):**
Same

**Browser and Operating System:**
Microsoft Edge Version 107.0.1418.35 (Official build) (64-bit) // Windows 11

**Description of problem:**

Trying to add the card, and getting very few options available to configure even with 2 weather integrations installed.  See...

![image](https://user-images.githubusercontent.com/100124187/200480821-90c535c4-8de6-4e63-8fa2-c92a248b4a99.png)

**Additional information:**

Happy to provide anything additional, though you may need to direct me where to find it.

**Comment by Makin-Things** [comment]
HA 2022.11 breaks loading the picker elements and therefore are simply not there. I have asked the devs for advice/assistance but they so far have not been at all helpful.
As a workaround if you add a button and an entity card on the same view it will work properly.

**Comment by wgumaa** [comment]
This is marked closed. But it’s not fixed!

**Comment by Makin-Things** [comment]
It was closed by the person with the original issue. I guess as they were ok with the workaround.
@chicknlil I am reopening as the problem isn't actually fixed.
I have a potential way forward thanks to another card author that has suggested a solution. I won't get a chance to try it until the weekend.

**Comment by pbranly** [comment]
Hi
What do you mean with "As a workaround if you add a button and an entity card on the same view it will work properly." ?
Where and what add ?
Phil

**Comment by rudizl** [comment]
On the same view where your weather card is add another button or entity card. It doesn't matter what it will contain.

**Comment by pbranly** [comment]
Hi 
I have installed your card in a view where there are already several cards.
I tried to add another one without success.
When I open PWC, I don’t have any mean to introduce existing weather input 
Phil

**Comment by Makin-Things** [comment]
A pre-release 1.0.3b0 has been published to try and fix everything that HA 2022.11 broke.
Please try it out and let me know how it goes.

**Comment by pbranly** [comment]
Hi
Sorry but I still don’t have any possibility to enter a weather forecast entity with this prerelease Version
Phil

**Comment by rudizl** [comment]
> A pre-release 1.0.3b0 has been published to try and fix everything that HA 2022.11 broke. Please try it out and let me know how it goes.

Works perfect for me, thanks.

**Comment by Makin-Things** [comment]
> Hi Sorry but I still don’t have any possibility to enter a weather forecast entity with this prerelease Version Phil

Make you you have done a hard refresh of the card. If that doesn't work for you I will need more information, screenshots etc.

**Comment by Makin-Things** [comment]
1.0.3 has been released that fixes this.
