### ISSUE TITLE
Daily Forecast Section looking for numerals?

### ISSUE THREAD

**Issue by chicknlil** [Makin-Things/platinum-weather-card#69]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
1.0.2

**Last working release (if known):**
n/a

**Browser and Operating System:**
Microsoft Edge Version 107.0.1418.35 (Official build) (64-bit)
Microsoft Windows 11

**Description of problem:**

Have added a Platinum Weather Card to my dashboard, an in trying to fill out the Daily Forecast Section, I provide the same weather data I provided elsewhere in the card, but it kicks back the following errors:

```
'entity_forecast_icon_1=sensor.pirateweather_icon' value needs to have a number
'entity_summary_1=sensor.pirateweather_summary' value needs to have a number
'entity_forecast_min_1=sensor.pirateweather_temperature' value needs to have a number
'entity_forecast_max_1=sensor.pirateweather_temperature' value needs to have a number
'entity_pop_1=sensor.pirateweather_precip_probability' value needs to have a number
'entity_pos_1=sensor.pirateweather_precip' value needs to have a number
```

Why is it looking for numbers here?  The information priate weather provided was sufficient for elsewhere in the card, why is it not here?

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

This card seems very buggy in general.  It says I can customize the colors, I haven't been able to.  Even setting up the card was a challenge, it took adding other cards to that dash before it let me select my calendars.

**Comment by Makin-Things** [comment]
For forecasts it is looking to find a number of different days, so it needs some sort of indexed data source.
I have not used pirateweather and since it requires registration for use I am not going to install it. There are so many different weather integrations that it is simply not possible for one person with a full time job to install and test them all.
If you were to include a dump of what sensors the piratewaether integration provides I may be able to point you in the right direction, but with the info provided so far I have nothing to work from.

The reason for needing to add the extra cards is because the HA devs changed stuff in 2022.11 and I have been unable to solicit any assistance from them to resolve the issue. It's not my fault that it got broken.

**Comment by chicknlil** [comment]
Please advise how to provide the dump.

**Comment by Makin-Things** [comment]
Not sure what sensor the pirateweather stuff creates. The doco for it doesn't mention that at all. But go to ``developer tools`` -> ``states`` and look for things it creates. Try filtering using ```weather`` and/or ``pirate`` etc.

**Comment by chicknlil** [comment]
```
sensor.pirateweather_alerts
sensor.pirateweather_apparent_temperature
sensor.pirateweather_cloud_coverage
sensor.pirateweather_dew_point
sensor.pirateweather_hourly_summary
sensor.pirateweather_humidity
sensor.pirateweather_icon
sensor.pirateweather_nearest_storm_distance
sensor.pirateweather_ozone
sensor.pirateweather_precip
sensor.pirateweather_precip_intensity
sensor.pirateweather_precip_probability
sensor.pirateweather_pressure
sensor.pirateweather_summary
sensor.pirateweather_temperature
sensor.pirateweather_uv_index
sensor.pirateweather_visibility
sensor.pirateweather_wind_bearing
sensor.pirateweather_wind_gust
sensor.pirateweather_wind_speed
```

I've requested a few of the temperature ones (min, max, high, low) but haven't heard back yet.

**Comment by chicknlil** [comment]
Aside, but although I'm providing precip_probability and precip to today's forecast rainfall (and it's raining and was forecasted to rain), it's showing 0.0 in.

**Comment by advisorgee** [comment]
I was having the same issue, what I did to correct this; use the code editor for the card and change the entity_pop_1 to sensor.pirateweather_precip_probability_1d

**Comment by chicknlil** [comment]
> I was having the same issue, what I did to correct this; use the code editor for the card and change the entity_pop_1 to sensor.pirateweather_precip_probability_1d

Nice catch.  I hadn't realized I was still having this issue, but I tweaked it based on your reply and lo and behold, I have an actual percip probability now! Kudos, @advisorgee !
