### ISSUE TITLE
Slot section: allow choosing number of colums

### ISSUE THREAD

**Issue by Soukyuu** [Makin-Things/platinum-weather-card#77]
With the data I'm using in my slots, there is a lot of unused space in the slot section and the alignment looks a bit out of place:

![image](https://user-images.githubusercontent.com/2095054/210826147-2d42f04c-51a0-4c57-b4f8-b83a740fba7c.png)

I've seen that other integrations seem to be more verbose (using open weather map myself), but having an option to have 3 (or even maybe 4) columns instead would be great. Avoiding the possible overlap/trimming of text would be in the hands of the user.

Now that I look at it, the whole alignment of the slot section seems to be off compared to the overview and forecast sections.

**Comment by Makin-Things** [comment]
Each section is completely separate, so there is now way to ensure alignment (the forecast for example can be anywhere from 1 to 5 columns).  Sorry but I am not even going to entertain the idea of making the number of columns in the slot section configurable as it would just cause too many issues to be raised,
